<a href="https://colab.research.google.com/github/unknown-jun/Basic_of_Python/blob/master/22_Dec_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- 공항 검색대에 입국할 때 위반되는 물건을 반입하려고 하면 못하게 막기 위해 사람이 모니터링 하는데 딥러닝 기술로 컴퓨터가 알아내게끔 기술을 구현하고 있음

In [ ]:
# 예제 1. c 드라이브 밑에 images 폴더에 있는 사진들의 이름을 불러오는 함수를 생성함
import os
test_image = []

def image_load(path):
    file_list = os.listdir(path)  # 해당 디렉토리의 파일명을 추출한다.
    return file_list

print( image_load(test_image) )

In [ ]:
# 예제 2. 위의 결과에서 숫자만 나오게 함수의 코드를 수정하시오
import os
import re # 데이터 정제를 전문으로 하는 모듈

test_image = '폐사진.zip'

def image_load(path):
    file_list = os.listdir(path)  # 해당 디렉토리의 파일명을 추출한다.
    file_name = []
    for i in file_list:
        a = re.sub('[^0-9]','',i)  # i의 값 중에서 숫자가 아닌 것들은 싱글 두개를 붙인 것('')
        file_name.append(a)        # 인 null로 변경
    return file_name                         
print( image_load(test_image) )

In [ ]:
# 문제 475. 위에서 출력되고 리스트 안의 요소들은 문자입니다. 그 리스트의 요소들이 숫자가 되게 하시오
import os
import re # 데이터 정제를 전문으로 하는 모듈

test_image = '/Users/LeeJunhyeok/Documents/python/폐사진'

def image_load(path):
    file_list = os.listdir(path)  # 해당 디렉토리의 파일명을 추출한다.
    file_name = []
    for i in file_list:
        a = re.sub('[^0-9]','',i)  # i의 값 중에서 숫자가 아닌 것들은 싱글 두개를 붙인 것('')
        file_name.append( int(a) )        # 인 null로 변경
    return file_name                         
print( image_load(test_image) )

In [ ]:
# 문제 476. 위의 리스트의 요소가 ascendgin 하게 정렬되게 하시오
import os
import re # 데이터 정제를 전문으로 하는 모듈

test_image = '/Users/LeeJunhyeok/Documents/python/폐사진'

def image_load(path):
    file_list = os.listdir(path)  # 해당 디렉토리의 파일명을 추출한다.
    file_name = []
    for i in file_list:
        a = re.sub('[^0-9]','',i)  # i의 값 중에서 숫자가 아닌 것들은 싱글 두개를 붙인 것('')
        file_name.append( int(a) ) # 인 null로 변경
        file_name.sort()           # sort 함수를 이용하여 정렬
    return file_name                         
print( image_load(test_image) )

In [ ]:
# 문제 477. 위의 함수의 코드를 추가해서 아래와 같이 출력되게 하시오

"""
['1.png', '2.png', '3.png', ... , '20.png']
"""

import os
import re # 데이터 정제를 전문으로 하는 모듈

test_image = '/Users/LeeJunhyeok/Documents/python/폐사진'

def image_load(path):
    file_list = os.listdir(path)  # 해당 디렉토리의 파일명을 추출한다.
    file_name = []
    for i in file_list:
        a = re.sub('[^0-9]','',i)  # i의 값 중에서 숫자가 아닌 것들은 싱글 두개를 붙인 것('')
        file_name.append( int(a) ) # 인 null로 변경
        file_name.sort()           # sort 함수를 이용하여 정렬
    
    file_res = []
    for k in file_name:
        file_res.append( str(k) + '.png' )    
    return file_res                         
print( image_load(test_image) )

In [ ]:
# 문제 478. 위의 함수의 코드를 수정해서 아래와 같이 이름 앞에 절대 경로가 붙게 하시오
"""
['/Users/LeeJunhyeok/Documents/python/폐사진/1.png', 
 '/Users/LeeJunhyeok/Documents/python/폐사진/2.png', 
 '/Users/LeeJunhyeok/Documents/python/폐사진3.png',
 ... ,
 '/Users/LeeJunhyeok/Documents/python/폐사진20.png']
"""
import os
import re # 데이터 정제를 전문으로 하는 모듈

test_image = '/Users/LeeJunhyeok/Documents/python/폐사진'

def image_load(path):
    file_list = os.listdir(path)  # 해당 디렉토리의 파일명을 추출한다.
    file_name = []
    for i in file_list:
        a = re.sub('[^0-9]','',i)  # i의 값 중에서 숫자가 아닌 것들은 싱글 두개를 붙인 것('')
        file_name.append( int(a) ) # 인 null로 변경
        file_name.sort()           # sort 함수를 이용하여 정렬
    
    file_res = []
    for k in file_name:
        file_res.append( '/Users/LeeJunhyeok/Documents/python/폐사진' + str(k) + '.png' )    
    return file_res                         
print( image_load(test_image) )

예제 3. 폐사진 이미지를 숫자로 변환하기 위해서 필요한 파이썬 모듈을 install 하시오
~~~
conda install opencv
~~~
~~~
pip install opencv-python
~~~

- opencv 모듈은 이미지를 파이썬에서 숫자로 변환하고 다양한 이미지 처리를 할 수 있게 해주는 기술을 제공해줌
- 예: 구글 지도나 카카오 지도, 네이버 지도에 보면 street view가 있는데 거기에 사람 얼굴이나 자동차 번호판을 모자이크 처리를 해줘야 함


In [ ]:
# 예제 4. 위에서 설치한 opencv모듈을 이용해서 폐사진을 숫자로 변환


In [ ]:
# 예제 5. 위의 숫자로 변환한 리스트를 인공 신경망에 넣기 위해서는 numpy 모듈의 array 형태로 제공해줘야 함
# 위의 리스트를 numpy array로 변환함
import numpy as np  # 랭렬 연산을 쉽고 빠르게 할 수 있게 해주는 모듈
import os
import re # 데이터 정제를 전문으로 하는 모듈

test_image = '/Users/LeeJunhyeok/Documents/python/폐사진'

def image_load(path):
    file_list = os.listdir(path)  # 해당 디렉토리의 파일명을 추출한다.
    file_name = []
    for i in file_list:
        a = re.sub('[^0-9]','',i)  # i의 값 중에서 숫자가 아닌 것들은 싱글 두개를 붙인 것('')
        file_name.append( int(a) ) # 인 null로 변경
        file_name.sort()           # sort 함수를 이용하여 정렬
    
    file_res = []
    for k in file_name:
        file_res.append( '/Users/LeeJunhyeok/Documents/python/폐사진' + str(k) + '.png' )    
    return file_res                         

print( image_load(test_image) )

In [ ]:
# 예제 4. 위의 개사진 이름에서 숫자만 출력하시오 
import os
import re

path = '/Users/LeeJunhyeok/Documents/python/dog'
def image_load2(path):
    file_list = os.listdir(path)
    file_name = []
    for i in file_list:
        a = re.sub('[^0-9]', '', i)
        file_name.append( int(a) )
    return file_name

print( image_load2(path))

In [ ]:
# 예제 5. file_nanme 리스트 안의 숫자를 정렬해서 출력되게 하시오
import os
import re

path = '/Users/LeeJunhyeok/Documents/python/dog'
def image_load2(path):
    file_list = os.listdir(path)
    file_name = []
    for i in file_list:
        a = re.sub('[^0-9]', '', i)
        file_name.append( int(a) )
        file_name.sort()
    return file_name

print( image_load2(path))

In [ ]:
# 예제 6. 아래와 같이 절대경로와 확장자가 붙어서 출력되게 하시오!
"""
['/Users/LeeJunhyeok/Documents/python/dog/1.png', 
 '/Users/LeeJunhyeok/Documents/python/dog/2.png', 
 '/Users/LeeJunhyeok/Documents/python/dog/3.png',
 ... ,
 '/Users/LeeJunhyeok/Documents/python/dog/20.png']
"""
import os
import re

path = '/Users/LeeJunhyeok/Documents/python/dog'
def image_load2(path):
    file_list = os.listdir(path)
    file_name = []
    for i in file_list:
        a = re.sub('[^0-9]', '', i)
        file_name.append( int(a) )
        file_name.sort()

    file_res=[]
    for k in file_name:
        file_res.append('Users/LeeJunhyeok/Documents/python/dog'+str(k)+'.jpg')
    
    return file_res

print( image_load2(path))

In [ ]:
# 예제 7. 위의 개 사진 이미지들을 opencv와 numpy를 이용해서 숫자로 변환하고 numpy array로 반환되게 하시오

import os
import re
import numpy as np
path = '/Users/LeeJunhyeok/Documents/python/dog'

def image_load2(path):
    file_list = os.listdir(path)
    file_name = []
    for i in file_list:
        a = re.sub('[^0-9]', '', i)
        file_name.append( int(a) )
        file_name.sort()

    file_res=[]
    for k in file_name:
        file_res.append('Users/LeeJunhyeok/Documents/python/dog.'+str(k)+'.jpg')
    
    image = []
    for h in file_res:
        img = cv2.imread(h)
        image.append(img)

    return np.array(image)

print( image_load2(path))

In [ ]:
# 문제 480. 지난 번에 직접 스크롤링한 사진 20장을 images3에 넣고 숫자로 변환하는 함수를 image_load3로 생성하시오

#152. 필수 알고리즘1 (합성곱 연산)
- 알고리즘 문제를 풀어야 하는 이유?
1. 지금까지 배운 파이썬 문법을 완성하는 단계 - 알고리즘 문제 해결
2. 구글, 네이버, 카카오와 같이 대기업으로 지원하고자 하면 알고리즘 문제를 많이 풀어봐야 함

- 프로그래머스 사이트에 여러 알고리즘 문제들이 올라와 있음
- 하루에 하나씩 꾸준히 풀면서 실력을 천천히 쌓아올리면 됨

- 합성곱 연산 알고리즘
    - 딥러닝의 필수 알고리즘: 퍼셉트론, 합성곱 연산 알고리즘
    - 이미지의 형상을 무시하지 않고 이미지를 그대로 인공 신경망이 학습 할 수 있게 해준 수학 행렬 연산
    - 합성곱에서 원본 이미지는 학습해야 할 데이터(사진)이고 필터(filter)는 원본 이미지에서 특징을 잡아내는 데 사용되는 행렬
    - 특징을 잡아서 feature map을 생성하여 원본 이미지의 형태를 이해하는 것을 합성곱 연산이라고 함

문제 481. 아래의 두 행렬을 만들고 덧셈 연산을 하시오
~~~
| 1  2  3  |       | 2  0  1  |
| 0  1  2  |   +   | 0  1  2  |
| 3  0  1  |       | 1  0  2  |
~~~

In [ ]:
import numpy as np

a = [[1, 2, 3], [0, 1, 2], [3, 0, 1]] 
b = [[2, 0, 1], [0, 1, 2], [1, 0, 2]]
a2 = np.array(a)
b2 = np.array(b)
print(a2)
print(b2,'\n')
print( a2 + b2 )

[[1 2 3]
 [0 1 2]
 [3 0 1]]
[[2 0 1]
 [0 1 2]
 [1 0 2]] 

[[3 2 4]
 [0 2 4]
 [4 0 3]]


문제 482. 아래의 두 행렬을 만들고 두 행렬의 원소들의 곱을 구하시오
~~~
| 1  2  3 |          | 2  0  1 |
| 0  1  2 |     *    | 0  1  2 |
| 3  0  1 |          | 1  0  2 |
~~~

In [ ]:
import numpy as np

a = [[1, 2, 3], [0, 1, 2], [3, 0, 1]]
b = [[2, 0, 1], [0, 1, 2], [1, 0, 2]]

a = np.array(a)
b = np.array(b)

print(a * b)

[[2 0 3]
 [0 1 4]
 [3 0 2]]


문제 483. 위의 원소들의 곱으로 출력된 결과인 3 X 3 행렬의 요소들을 모두다 더하시오   
결과 : 15

In [ ]:
import numpy as np

a = [[1, 2, 3], [0, 1, 2], [3, 0, 1]]
b = [[2, 0, 1], [0, 1, 2], [1, 0, 2]]

a2 = np.array(a)
b2 = np.array(b)

result =a2 * b2
print( np.sum(result) )

15


- numpy란 python 언어에서 기본적으로 지원하지 않는 배열(array) 혹은 행렬(matrix)의 계산을 쉽게 해주는 라이브러리
- 머신러닝에서 많이 사용하는 선형대수학에 관련된 수식들을 python에서 쉽게 프로그래밍 할 수 있게 해줌

문제 484. 아래의 4x4 행렬을 만드시오
~~~
| 1  2  3  0  |
| 0  1  2  3  |
| 3  0  1  2  | 
| 2  3  0  1  | 
~~~

In [ ]:
a = [[1, 2, 3, 0], [0, 1, 2, 3], [3, 0, 1, 2], [2, 3, 0, 1]]
a2 = np.array(a)
print(a2)

[[1 2 3 0]
 [0 1 2 3]
 [3 0 1 2]
 [2 3 0 1]]


문제 485. 위의 4 X 4 행렬에서 **으로 지정한 영역의 숫자들만 출력하시오
~~~
  *  *  *
|* 1  2  3 * 0  |    행이 1부터 3까지
|* 0  1  2 * 3  |    열도 1부터 3까지
|* 3  0  1 * 2  | 
  *  *  *
|  2  3  0  1  | 
~~~

In [ ]:
a = [[1, 2, 3, 0], [0, 1, 2, 3], [3, 0, 1, 2], [2, 3, 0, 1]]
a2 = np.array(a)
print( a2[0:3, 0:3] ) # 행을 0 이상에서 3 미만까지 
                      # 열을 0 이상에서 3 미만까지
                    

[[1 2 3]
 [0 1 2]
 [3 0 1]]


문제 486. 아래의 4 x 4행렬에서 **으로 지정한 영역의 숫자들만 출력하시오

~~~
       *  *  *
| 1 *  2  3  0 * |    
| 0 *  1  2  3 * |    
| 3 *  0  1  2 * | 
       *  *  *
| 2  3  0  1  | 
~~~

In [ ]:
import numpy as np
a = [[1, 2, 3, 0], [0, 1, 2, 3], [3, 0, 1, 2], [2, 3, 0, 1]]
a2 = np.array(a)
print( a2[0:3 , 1:4] )

[[2 3 0]
 [1 2 3]
 [0 1 2]]


문제 487. 아래의 4 x 4 행렬에서 **으로 지정한 영역의 숫자들만 출력하시오
~~~
    
| 1  2  3  0 |    
  *  *  *
|* 0  1  2 * 3 |    
|* 3  0  1 * 2 |
|* 2  3  0 * 1 | 
   *  *  *
~~~

In [ ]:
import numpy as np
a = [[1, 2, 3, 0], [0, 1, 2, 3], [3, 0, 1, 2], [2, 3, 0, 1]]
a2 = np.array(a)
print( a2[1:4 , 0:3] )

[[0 1 2]
 [3 0 1]
 [2 3 0]]


문제 488. 아래의 4 x 4 행렬에서 **으로 지정한 영역의 숫자들만 출력하시오
~~~
| 1  2  3  0 |    
      *  *  *
| 0 * 1  2  3 * |    
| 3 * 0  1  2 * |
| 2 * 3  0  1 * | 
      *  *  *
~~~

In [ ]:
import numpy as np
a = [[1, 2, 3, 0], [0, 1, 2, 3], [3, 0, 1, 2], [2, 3, 0, 1]]
a2 = np.array(a)

print( a2[1:4 , 1:4] )

[[1 2 3]
 [0 1 2]
 [3 0 1]]


문제 489. 위에서 **으로 지정한 4 X 4행렬의 네 영역의 숫자들을 for loop문을 이용해서 모두 출력하시오
~~~
| 1  2  3  0  |
| 0  1  2  3  |
| 3  0  1  2  | 
| 2  3  0  1  | 
~~~

In [ ]:
a = [[1, 2, 3, 0], [0, 1, 2, 3], [3, 0, 1, 2], [2, 3, 0, 1]]
a2 = np.array(a)
"""
print( a2[0:3 , 0:3] )
print( a2[0:3 , 1:4] )
print( a2[1:4 , 0:3] )
print( a2[1:4 , 1:4] )
"""
for i, k in zip(range(0,2), range(3,5)):
    for j, h in zip(range(0,2), range(3,5)):
        print(a2[i:k, j:h])

[[1 2 3]
 [0 1 2]
 [3 0 1]]
[[2 3 0]
 [1 2 3]
 [0 1 2]]
[[0 1 2]
 [3 0 1]
 [2 3 0]]
[[1 2 3]
 [0 1 2]
 [3 0 1]]


문제 490. 위에서 선택한 4개의 행렬(3x3)과 아래의 filter 행렬(3x3)과의 원소의 곱을 출력하시오
~~~
f=[ [ 2, 3, 4 ], [ 1, 2, 3 ], [ 2, 0, 1 ] ]
filter = np.array(f)
print(filter)
~~~

In [ ]:
f=[ [ 2, 3, 4 ], [ 1, 2, 3 ], [ 2, 0, 1 ] ]
filter = np.array(f)

a = [ [1,2,3,0] , [0,1,2,3] , [3,0,1,2] , [2,3,0,1]] 
for i in range(0,2):
    for j in range(0,2):
        print(a2[i:i+3,j:j+3] * filter )

[[ 2  6 12]
 [ 0  2  6]
 [ 6  0  1]]
[[4 9 0]
 [1 4 9]
 [0 0 2]]
[[0 3 8]
 [3 0 3]
 [4 0 0]]
[[ 2  6 12]
 [ 0  2  6]
 [ 6  0  1]]


문제 491. 위에서 출력된 3x3 행렬 4개에 대한 원소들의 합이 각각 출력되게 하시오
~~~
[[ 2  6 12]
 [ 0  2  6]   ---> 35
 [ 6  0  1]]

[[4 9 0]
 [1 4 9]     ----> 29
 [0 0 2]]

[[0 3 8]
 [3 0 3]     ----> 21
 [4 0 0]]

[[ 2  6 12]
 [ 0  2  6]   ----> 35
 [ 6  0  1]]
~~~


In [ ]:
f=[ [ 2, 3, 4 ], [ 1, 2, 3 ], [ 2, 0, 1 ] ]
filter = np.array(f)

a = [ [1,2,3,0] , [0,1,2,3] , [3,0,1,2] , [2,3,0,1]] 
for i in range(0,2):
    for j in range(0,2):
        print( np.sum( a2[i:i+3,j:j+3] * filter ) )

35
29
21
35


문제 492. 위에서 출력된 4개의 숫자로 아래의 행렬( 2x2 )을 만드시오
~~~~
| 35 29 |
| 21 35 |
~~~

In [ ]:
f=[ [ 2, 3, 4 ], [ 1, 2, 3 ], [ 2, 0, 1 ] ]
filter = np.array(f)

a = [ [1,2,3,0] , [0,1,2,3] , [3,0,1,2] , [2,3,0,1]] 

result = []
for i in range(0,2):
    for j in range(0,2):
        result.append( np.sum( a2[i:i+3,j:j+3] * filter ) ) 
        
result2 = np.array(result).reshape(2,2)   # numpy array의 2 x 2 행렬로 변환
print(result2)

[[35 29]
 [21 35]]


- a2 라는 원본 이미지( 개 사진 )에 filter( 랜덤으로 생성한 이미지 )를 가지고 원본이미지를 스트라이드( 양 옆 위 아래로 스캔 )하면서 특징 이미지를 추출( result2 )하는 것을 합성곱이라고 함

문제 493. 아래의 원본 이미지 행렬 (5 x 5 )행렬에서 필터 행렬( 4 x 4 )로 스트라이딩 해서 합성곱해서 특징을 추출하시오
~~~
a = [ [2,3,1,4,7],[3,1,6,4,3],[2,1,5,3,1],[6,2,4,1,2],[7,3,1,2,3] ]
f = [ [3,1,4,1],[2,3,3,4],[5,1,2,1],[6,1,3,4] ]
~~~

In [ ]:
a = [ [2,3,1,4,7],[3,1,6,4,3],[2,1,5,3,1],[6,2,4,1,2],[7,3,1,2,3] ]
mat_1 = np.array(a)

f = [ [3,1,4,1],[2,3,3,4],[5,1,2,1],[6,1,3,4] ]
mat_2 = np.array(f)

for i, k in zip(range(0,2), range(3,5)):
    for j, h in zip(range(0,2), range(3,5)):
        print( mat_1[i:i+4, j:j+4] * mat_2 )



[[ 6  3  4  4]
 [ 6  3 18 16]
 [10  1 10  3]
 [36  2 12  4]]
[[ 9  1 16  7]
 [ 2 18 12 12]
 [ 5  5  6  1]
 [12  4  3  8]]
[[ 9  1 24  4]
 [ 4  3 15 12]
 [30  2  8  1]
 [42  3  3  8]]
[[ 3  6 16  3]
 [ 2 15  9  4]
 [10  4  2  2]
 [18  1  6 12]]


#153. 필수 알고리즘2 (이진 탐색)

- 이진탐색: 정렬된 데이터를 좌우 둘로 나눠서 원하는 값의 탐색 범위를 좁혀가며 찾는 방법


문제 494. 아래의 리스트에서 숫자 3이 있는지 순차 탐색으로 구현하시오. 있으면 '숫자 3이 있습니다.'라는 메세지가 출력되게 하시오
~~~
a = [15, 11, 1, 3, 8]
~~~

In [ ]:
a = [15, 11, 1, 3, 8]

for i in a:
    if i == 3:
        print('숫자가 3이 있습니다')
        break
else:
    print('숫자 3이 아닙니다')

숫자가 3이 있습니다


문제 495. 위의 코드를 수정해서 숫자를 물어보게 하고 숫자를 입력하면 해당 숫자가 존재하는지 존재하지 않는지를 출력되게 하시오

In [ ]:
a = [15, 11, 1, 3, 8]
b = int(input('검색할 숫자를 입력하세요: '))

for i in a:
    if i == b:
        print('숫자가 '+ str(b) +'이 있습니다')
        break
else:
    print('숫자 '+ str(b) + '이 아닙니다')

검색할 숫자를 입력하세요: 7
숫자 7이 아닙니다


문제 496. 아래의 a 리스트에서 중앙값을 찾으시오
~~~
a = [ 1, 7, 11, 12, 14, 23, 33, 47, 51, 64, 67, 77, 139, 672, 871 ]
~~~

In [ ]:
import numpy as np

a = [ 1, 7, 11, 12, 14, 23, 33, 47, 51, 64, 67, 77, 139, 672, 871 ]

a_n = np.array( a )
print( np.median(a_n) )

47.0


문제 497. a 리스트에서 첫 번째 숫자부터 중앙값에 해당하는 숫자까지만 검색하시오
~~~
결과: [1, 7, 11, 12, 14, 23, 33, 47]
~~~

In [ ]:
import numpy as np

a = [ 1, 7, 11, 12, 14, 23, 33, 47, 51, 64, 67, 77, 139, 672, 871 ]

a_n = np.array( a )
a_m = np.median( a_n)
print( a[ :a.index(a_m)+1] )

[1, 7, 11, 12, 14, 23, 33, 47]


문제 498. 위의 a 리스트에서 문제 497번에서 선택된 숫자들을 중앙값까지 포함해서 다 지우고 아래의 결과만 출력되게 하시오
~~~
결과: [51, 64, 67, 77, 139, 672, 871 ]
~~~

In [ ]:
import numpy as np

a = [ 1, 7, 11, 12, 14, 23, 33, 47, 51, 64, 67, 77, 139, 672, 871 ]

a_n = np.array( a )
a_m = np.median( a_n)
del( a[ :a.index(a_m)+1] )
print(a)

[51, 64, 67, 77, 139, 672, 871]


문제 499. 위의 결과로 출력된 아래의 리스트에서 중앙값을 출력하시오

In [ ]:
import numpy as np

a = [ 1, 7, 11, 12, 14, 23, 33, 47, 51, 64, 67, 77, 139, 672, 871 ]

a_n = np.array( a )
a_m = np.median( a_n )

del( a[ :a.index(a_m)+1] )

a_m2 = np.median( a )
print( a_m2 ) 

77.0

문제 500. 위에서 출력한 중앙값 77이 내가 검색하고자 하는 67보다 크다면 아래의 결과 리스트만 출력되게 하시오
~~~
[51, 64, 67, 77, 139, 672, 871]
결과 [ 51, 64, 67 ]
~~~

In [ ]:
import numpy as np

a = [ 1, 7, 11, 12, 14, 23, 33, 47, 51, 64, 67, 77, 139, 672, 871 ]

a_n = np.array( a )
a_m = np.median( a_n )

del( a[ :a.index(a_m)+1] )

a_m2 = np.median( a )
if a_m2 > 67:
    del(a[ a.index(a_m2) : ])
else:
    del(a[: a.index(a_m2) +1 ])

print(a)

[51, 64, 67]


문제 501. <필수 알고리즘 2번> EBS에 나온 영상대로 이진탐색을 구현하시오
~~~
a = [ 1, 7, 11, 12, 14, 23, 33, 47, 51, 64, 67, 77, 139, 672, 871 ]

a 리스트에서 검색할 숫자를 입력하세요:    67
67은 이진탐색 3번만에 검색되었습니다.

a 리스트에서 검색할 숫자를 입력하세요:    68
68은 a 리스트에 없습니다.
~~~

In [151]:
import numpy as np

num = int(input("a 리스트에서 검색할 숫자를 입력하세요: "))

a = [ 1, 7, 11, 12, 14, 23, 33, 47, 51, 64, 67, 77, 139, 672, 871 ]

cnt = 0
while True:
    a_n = np.array(a)
    a_m = np.median(a_n)
    if num > a_m:
        del(a[  :a.index(a_m)+1])
        cnt += 1
    elif num < a_m:
        del(a[ a.index(a_m) :])
        cnt += 1
    elif num == a_m:
        print(f"{num}은 이진탐색 {cnt}번만에 검색되었습니다.")
        break
    else:
        print(f"{num}은 a 리스트에 없습니다.")
        break


a 리스트에서 검색할 숫자를 입력하세요: 12
12은 이진탐색 1번만에 검색되었습니다.
